# File: .github/workflows/hg-git.yml

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: "hg::https://foss.heptapod.net/mercurial/hg-git"
      DEST_REPO: "https://${{ github.actor }}:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/saschazepter/hg-git.git"
    steps:
    #- uses: actions/checkout@v4
    #  with:
    #    persist-credentials: false
    - run: |
        sudo add-apt-repository -y "ppa:git-core/ppa"
        sudo apt-get update
        sudo apt-get -y install git-remote-hg git-filter-repo

        git clone --mirror "$SOURCE_REPO" .
        git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin

        git config --unset-all http."https://github.com/".extraheader || :

        echo "Resetting origin to: $DEST_REPO"
        git remote set-url origin "$DEST_REPO"

        echo "Adding tmp_upstream $SOURCE_REPO"
        git remote add tmp_upstream "$SOURCE_REPO"

        echo "Fetching tmp_upstream"
        git fetch tmp_upstream --quiet
        git remote --verbose

        echo "Pushing changings from tmp_upstream to origin"
        git config --list
        git filter-repo --invert-paths --path-glob '*.git' --force; git push origin "*:*" --force #; git push origin --all --force; git push origin --tags --force

        echo "Removing tmp_upstream"
        git remote rm tmp_upstream
        git remote --verbose
