# File: .github/workflows/hg.yml

on:
#  schedule:
#  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: "https://repo.mercurial-scm.org/hg"
      DEST_REPO: "hg"
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: 'mozillazg/mirror-hg-repo@v2'
      with:
        source-hg-repo-url: '${{ env.SOURCE_REPO }}'
        destination-git-repo-owner: '${{ github.actor }}'
        destination-git-repo-name: '${{ env.DEST_REPO }}'
        destination-git-personal-token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
